User:
  name: Aquiles

Params:
  resistance: 100ohm
  port: /dev/cu.usbmodem14101
  device_type: dummy #(real or dummy)

Scan:
  start: 0V
  stop: 3300mV
  step: 100mV
  delay: 50ms
  channel_in: 0
  channel_out: 0

Saving:
  filename: IV_data
  path: /Users/Flo/data


